// Generated by CoffeeScript 1.4.0
(function() {

  Ext.define('ListHeaderFooter.model.Item', {
    extend: 'Ext.data.Model',
    config: {
      fields: [
        {
          name: 'item',
          type: 'string'
        }, {
          name: 'section_name',
          type: 'string'
        }
      ]
    }
  });

}).call(this);
